version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: .devcontainer/frontend.Dockerfile
    command: sleep infinity
    volumes:
      - .:/workspace:cached
    networks:
      - noumena_net

  backend:
    build:
      context: .
      dockerfile: .devcontainer/backend.Dockerfile
    command: sleep infinity
    volumes:
      - .:/workspace:cached
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - AZURE_STORAGE_QUEUE_CONNECTION_STRING=${AZURE_STORAGE_QUEUE_CONNECTION_STRING}
    depends_on:
      - database
    ports:
      - "5001:5000"
    networks:
      - noumena_net

  database:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password1234
    networks:
      - noumena_net

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - noumena_net

volumes:
  neo4j_data:

networks:
  noumena_net: