version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: .devcontainer/frontend.Dockerfile
    # commandをシンプルに変更
    command: npm run dev
    
    volumes:
      - .:/workspace:cached
      - /workspace/workspaces/frontend/node_modules
    environment:
      - NEXT_PUBLIC_BACKEND_API_URL=${NEXT_PUBLIC_BACKEND_API_URL}
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - noumena_net

  backend:
    build:
      context: .
      dockerfile: .devcontainer/backend.Dockerfile
    command: sh -c "cd /workspace/workspaces/backend && dotnet run"
    volumes:
      - .:/workspace:cached
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - AZURE_STORAGE_QUEUE_CONNECTION_STRING=${AZURE_STORAGE_QUEUE_CONNECTION_STRING}
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      - database
    ports:
      - "5001:5001"
    networks:
      - noumena_net

  database:
    image: neo4j:5
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password1234
    networks:
      - noumena_net

volumes:
  neo4j_data:

networks:
  noumena_net: